### ISSUE TITLE
Can't seem to import BDMEP data

### ISSUE THREAD

**Issue by daniel-althoff** [lhmet/inmetr#4]
I'm getting this message when I try to import:

------------------------------
station: 83579
Bad Request (HTTP 400).

my script:
library(inmetr)
head(bdmep_meta)
sort(unique(bdmep_meta$name))
stations<-c("Araxá")
stations_rows<-pmatch(stations, bdmep_meta$name)
bdmep_meta[stations_rows,]

stns_cods<- bdmep_meta[stations_rows,'id']
start_date <- "01/01/1961"
end_date <- format(Sys.Date(),' %d/%m/%Y')
met_data <- bdmep_import(id=stns_cods, sdate = start_date, edate = end_date, email= "myemail", passwd='mypass', verbose=T)
(just to be clear, my e-mail and password work fine on the BDMEP website)

I get bad request for all stations I've tried.
I followed the instructions, which were very clear... what I am doing wrong?
Thanks

**Comment by lhmet** [comment]
@danielalthoff try change your code at  
```{r}
end_date <- format(Sys.Date(),' %d/%m/%Y')
# replace it by
end_date <- format(Sys.Date(),'%d/%m/%Y')
```
that's make diference when the link to bdmep is build.
Anyway, I will put at the beginning of the function code the removal of white space from the arguments provided on the dates. This will prevent typing errors like that.
Please, let me know if that works for you.
Thank you.

**Comment by daniel-althoff** [comment]
Thank you!
